apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
- service.yaml
- deployment.yaml
- pvc.yaml
- dashboard-hook-ingressroute.yaml
- serviceaccount.yaml
- clusterrolebinding.yaml
- clusterrole.yaml
- middlewares.yaml
- serverstransports.yaml
- tlsstores.yaml
- traefikservices.yaml
- middlewarestcp.yaml
- ingressroute.yaml
- ingressrouteudp.yaml
- tlsoptions.yaml
- ingressroutetcp.yaml
