apiVersion: v1
items:
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    labels:
      k8s-app: traefik-ingress-lb
    name: traefik-ingress-controller
    namespace: traefik
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    template:
      metadata:
        creationTimestamp: null
        labels:
          k8s-app: traefik-ingress-lb
          name: traefik-ingress-lb
      spec:
        containers:
        - args:
          - --providers.kubernetesingress=true
          - --providers.kubernetesingress.ingressendpoint.ip=127.0.0.1
          - --api.dashboard=true
          - --api.insecure=true
          - --log=true
          - --log.level=INFO
          - --accesslog=true
          - --accesslog.filepath=/dev/stdout
          - --accesslog.format=json
          - --entrypoints.web.address=:80
          - --entrypoints.websecure.address=:443
          image: traefik:2.3
          imagePullPolicy: IfNotPresent
          name: traefik-ingress-lb
          ports:
          - containerPort: 8080
            hostPort: 8080
            name: http
            protocol: TCP
          resources: {}
          securityContext:
            capabilities:
              add:
              - NET_BIND_SERVICE
              drop:
              - ALL
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        hostNetwork: true
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: traefik-ingress-controller
        serviceAccountName: traefik-ingress-controller
        terminationGracePeriodSeconds: 60
        tolerations:
        - effect: NoSchedule
          operator: Exists
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
