apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-cd
resources:
- dex/serviceaccount.yaml
- dex/role.yaml
- dex/service.yaml
- dex/rolebinding.yaml
- dex/deployment.yaml
- argocd-configs/argocd-cm.yaml
- argocd-configs/argocd-tls-certs-cm.yaml
- argocd-configs/argocd-rbac-cm.yaml
- argocd-configs/argocd-ssh-known-hosts-cm.yaml
- argocd-configs/argocd-gpg-keys-cm.yaml
- argocd-configs/argocd-secret.yaml
- argocd-application-controller/serviceaccount.yaml
- argocd-application-controller/clusterrolebinding.yaml
- argocd-application-controller/role.yaml
- argocd-application-controller/clusterrole.yaml
- argocd-application-controller/service.yaml
- argocd-application-controller/rolebinding.yaml
- argocd-application-controller/deployment.yaml
- argocd-server/serviceaccount.yaml
- argocd-server/clusterrolebinding.yaml
- argocd-server/role.yaml
- argocd-server/clusterrole.yaml
- argocd-server/service.yaml
- argocd-server/rolebinding.yaml
- argocd-server/deployment.yaml
- argocd-repo-server/service.yaml
- argocd-repo-server/deployment.yaml
- redis/service.yaml
- redis/deployment.yaml
