bases:
- ../../base/traefik
resources:
- namespace.yaml
- dashboard-middleware.yaml

secretGenerator:
- name: cloudflare-credentials
  namespace: traefik
  envs:
  - cloudflare.env
  type: Opaque
- name: dashboard-certs
  namespace: traefik
  files:
  - tls.crt
  - tls.key
  type: Opaque

configMapGenerator:
- name: static-config
  namespace: traefik
  files:
  - dynamic.yaml
