ports:
  traefik:
    port: 9000
  web:
    port: 8080
    expose: true
    exposedPort: 80
  websecure:
    port: 8443
    expose: true
    exposedPort: 443

additionalArguments:
- --api.insecure=true
