hostNetwork: true
ports:
  traefik:
    port: 9080
    #expose: true
    #exposedPort: 9080
  web:
    port: 80
    expose: true
    exposedPort: 80
  websecure:
    port: 443
    expose: true
    exposedPort: 443

# Allow ports under 1024
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0

#volumes:
#  - name: traefik-dashboard-certs
#    mountPath: "/certs"
#    type: secret

initContainers:
- name: volume-permissions
  image: busybox:1.31.1
  command: ["sh", "-c", "chmod -Rv 600 /data/*"]
  volumeMounts:
    - name: data
      mountPath: /data

envFrom:
- secretRef:
    name: cloudflare-credentials

additionalArguments:
#- --api.insecure=true
- --log.level=DEBUG
- --accesslog=true
- --serversTransport.insecureSkipVerify=true
# Setup secure traefik entrypoint
- --entryPoints.traefiksecure.address=:9443/tcp
- --entryPoints.traefiksecure.http.tls=true
- --entrypoints.traefiksecure.http.tls.certResolver=letsencrypt
- --entrypoints.traefiksecure.http.tls.domains[0].main=timostroehlein.com
- --entrypoints.traefiksecure.http.tls.domains[0].sans=*.timostroehlein.com
# Setup an insecure listener that redirects all traffic to TLS
#- --entrypoints.web.http.redirections.entrypoint.to=websecure
#- --entrypoints.web.http.redirections.entrypoint.scheme=https
# Setup the TLS configuration for our websecure listener
- --entrypoints.websecure.http.tls=true
- --entrypoints.websecure.http.tls.certResolver=letsencrypt
- --entrypoints.websecure.http.tls.domains[0].main=timostroehlein.com
- --entrypoints.websecure.http.tls.domains[0].sans=*.timostroehlein.com
  # Setup LetsEncrypt
- --certificatesresolvers.letsencrypt.acme.dnschallenge=true
- --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
- --certificatesresolvers.letsencrypt.acme.email=timostroehlein@gmail.com
- --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
#- --certificatesresolvers.letsencrypt.acme.caServer=https://acme-v02.api.letsencrypt.org/directory
- --certificatesresolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
