hostNetwork: true
ports:
  traefik:
    port: 9000
  web:
    port: 80
    expose: true
    exposedPort: 80
  websecure:
    port: 443
    expose: true
    exposedPort: 443

# Allow ports under 1024
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0

#volumes:
#  - name: traefik-dashboard-certs
#    mountPath: "/certs"
#    type: secret

additionalArguments:
- --api.insecure=true
- --log.level=DEBUG
- --accesslog=true
- --serversTransport.insecureSkipVerify=true
- --certificatesresolvers.letsencrypt.acme.dnschallenge=true
- --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
- --certificatesresolvers.letsencrypt.acme.email=timostroehlein@gmail.com
- --certificatesresolvers.letsencrypt.acme.storage=/data/letsencrypt/acme.json
- --certificatesresolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
