hostNetwork: true
ports:
  traefik:
    port: 8000
  web:
    port: 80
    expose: true
    exposedPort: 80
  websecure:
    port: 443
    expose: false
    exposedPort: 443

securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0

additionalArguments:
- --api.insecure=true
- --log.level=DEBUG
- --accesslog=true
